### ISSUE TITLE
Nothing response after press some hostkey

### ISSUE THREAD

**Issue by flying1020** [ITachiLab/hotkey-detective#1]
OS: win10, version: 19041.572
presse win+a, win+s, alter+tab, work well.
press ctrl+n, ctrl+shift+n, nothing response on shell.

**Comment by ITachiLab** [comment]
Hi, thanks for the report!

Do you suspect that CTRL+N or CTRL+SHIFT+N are owned by some process? HotKey Detective recognises only the hotkeys that are registered with the system. These combinations looks like they belong to a browser and can be received only when the browser is a top most window. In this case, the browser could have a different method of catching the key combinations and it might not use the system's API.

If I understood you wrong, please give more details on how did you check that and what is the expected result.

**Comment by flying1020** [comment]
you right.
ctrl + x are not owned by system.
it`s feature.

**Comment by ITachiLab** [comment]
Actually, there's a possibility to create a global, system hotkey for `CTRL + X` combination, but almost no one does it. The reason is simple: many programs leverage `CTRL + X` for their internal purposes, like mentioned `CTRL + N` in a browser, and the global hotkey will mostly override the internal behavior. Developers know this and avoid using `CTRL + (letter)` combinations for their global bindings.

`ALT + (letter)` is a different story though. It's a common practice to use this kind of combination as a global hotkey because it has no practical usage in case of languages without diacritics (like English).
