### ISSUE TITLE
No hotkeys caught: Windows 10; hotKeyDetective 0.1

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ITachiLab/hotkey-detective#3]
Windows 10,  2009 (19042), x64, with your program running as an administrator.

Thank you for the program. However: the program catches - displays information about - no hotkeys whatsoever: win-a; ctrl-alt-f; ctrl-alt-k; printScrn. EDIT: But, ah, it caught one alt-tab.

**Comment by LinuxOnTheDesktop** [comment]
But, ah, I had something in RAM that was messing things up: after rebooting, the program detected various hotkeys, although: it did so rather slowly; even registering ctrl-C (to quit the program) was slow; the program reported 'unknown process' for a hotkey owned by the program KeePassXC.

**Comment by ITachiLab** [comment]
Hi, thanks for your observations! I'm not sure what could cause the problem with HotKey Detective being slow, however, it could be due to its console nature. I'm currently in progress of making it a GUI application (#2), as the current version is rather a prototype. Come over soon, and test the GUI version :).
